RedutaOrdona = "Nam strzelać nie kazano. Wstąpiłem na działo. I spojrzałem na pole, dwieście armat grzmiało. Artyleryji ruskiej ciągną się szeregi, Prosto, długo, daleko, jako morza brzegi."
print (RedutaOrdona.count("a"))
print (RedutaOrdona.count("e"))
print (RedutaOrdona.count("i"))
print (RedutaOrdona.count("o"))
print (RedutaOrdona.count("u"))
print (RedutaOrdona.count("y"))
print (RedutaOrdona.count("ą"))
print (RedutaOrdona.count("ę"))
print (RedutaOrdona.count("ó"))

a = RedutaOrdona.count("a")
b = RedutaOrdona.count("e")
c = RedutaOrdona.count("i")
d = RedutaOrdona.count("o")
e = RedutaOrdona.count("u")
f = RedutaOrdona.count("y")
g = RedutaOrdona.count("ą")
h = RedutaOrdona.count("ę")
i = RedutaOrdona.count("ó")
print(a+b+c+d+e+f+g+h+i)